
FROM postgres:14-alpine

# Biến môi trường sẽ được cung cấp bởi docker-compose.yml
# Sao chép các script khởi tạo
COPY ./deployment/database/init-scripts/ /docker-entrypoint-initdb.d/

EXPOSE 5432

# Sử dụng health check để đảm bảo cơ sở dữ liệu sẵn sàng
HEALTHCHECK --interval=5s --timeout=5s --retries=3 \
  CMD pg_isready -U postgres || exit 1
