
version: '3.8'

services:
  # Database Service
  postgres-db:
    build:
      context: .
      dockerfile: deployment/database/Dockerfile
    container_name: alzheimer-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: alzheimer_diagnosing
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend-network
    restart: unless-stopped
    ports:
      - "5432:5432"

  # Backend Services
  auth-service:
    build:
      context: .
      dockerfile: deployment/backend/auth-service/Dockerfile
    container_name: alzheimer-auth-service
    environment:
      NODE_ENV: production
      DB_HOST: postgres-db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: alzheimer_diagnosing
    depends_on:
      - postgres-db
    networks:
      - backend-network
    restart: unless-stopped
    ports:
      - "3001:3001"

  diagnostic-service:
    build:
      context: .
      dockerfile: deployment/backend/diagnostic-service/Dockerfile
    container_name: alzheimer-diagnostic-service
    environment:
      NODE_ENV: production
      DB_HOST: postgres-db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: alzheimer_diagnosing
    depends_on:
      - postgres-db
    networks:
      - backend-network
    restart: unless-stopped
    ports:
      - "3002:3002"

  mri-service:
    build:
      context: .
      dockerfile: deployment/backend/mri-service/Dockerfile
    container_name: alzheimer-mri-service
    environment:
      NODE_ENV: production
      DB_HOST: postgres-db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: alzheimer_diagnosing
    depends_on:
      - postgres-db
    networks:
      - backend-network
    volumes:
      - mri-uploads:/app/uploads
    restart: unless-stopped
    ports:
      - "3003:3003"

  # Frontend Service
  frontend:
    build:
      context: .
      dockerfile: deployment/frontend/Dockerfile
    container_name: alzheimer-frontend
    depends_on:
      - auth-service
      - diagnostic-service
      - mri-service
    networks:
      - frontend-network
      - backend-network
    restart: unless-stopped
    ports:
      - "8080:80"

# Networks
networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge

# Volumes
volumes:
  postgres-data:
    driver: local
  mri-uploads:
    driver: local
